apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gdb-attach-test-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      shareProcessNamespace: true 
      volumes:
      - name: data-volume 
        emptyDir:
      initContainers:
      - name: prepare-app
        image: testapp:0.1
        command: ["sh", -c]
        args:
          - cp
            /home/app
            /data
        volumeMounts:
          - name:  data-volume
            mountPath:  /data
      - name: prepare-debugtool
        image: debugtool:0.1
        command: ["sh", -c]
        args:
          - cp
            /data/app
            /home
        volumeMounts:
          - name:  data-volume
            mountPath:  /data
      containers:
      - name: app
        image: testapp:0.1
        command: ["/home/app"]
        resources:
          requests:  
            cpu: 100m
            memory: 200Mi
            ephemeral-storage: "100Mi"
          limits:
            cpu: 200m
            memory: 400Mi
            ephemeral-storage: "200Mi"
      - name: debugtool
        image: debugtool:0.1
        command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
            ephemeral-storage: "100Mi"
          limits:
            cpu: 200m
            memory: 400Mi
            ephemeral-storage: "200Mi"
        securityContext:
          capabilities:
              add:
              - SYS_PTRACE #for gdb strace
        volumeMounts:
          - name:  data-volume
            mountPath:  /data
